# Generated by Django 2.1.15 on 2022-10-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skcone', '0004_auto_20221010_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'System',
            },
        ),
        migrations.CreateModel(
            name='testR1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'testR1',
            },
        ),
    ]
