# Generated by Django 2.1.15 on 2022-10-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skcone', '0005_system_testr1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('SystemName', models.CharField(max_length=20)),
                ('DocStatus', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('RequesterCode', models.CharField(max_length=10)),
                ('RequestDate', models.DateTimeField(null=True)),
                ('LastUpdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-RequestDate',),
            },
        ),
        migrations.CreateModel(
            name='UrlSystemapi',
            fields=[
                ('SystemID', models.AutoField(primary_key=True, serialize=False)),
                ('NameSystemUrl', models.CharField(max_length=20)),
                ('Url', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='System',
        ),
        migrations.DeleteModel(
            name='testR1',
        ),
        migrations.DeleteModel(
            name='testRequest',
        ),
    ]
